# Generated by Django 4.2 on 2023-06-19 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bicicleta_repuestos_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Id de Marca')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('idModelo', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Id de Modelo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Modelo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marca')),
            ],
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marca'),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modelo'),
        ),
    ]
